### ISSUE TITLE
Reconsider using Pkg server by default for the registry

### ISSUE THREAD

**Issue by KristofferC** [julia-actions/julia-buildpkg#14]
In 1.7, Pkg has moved to use a compressed registry by default. This avoids unpacking ~22 000 files and has some good performance improvements for the first time installing a registry (which is what CI does all the time):

**git** :

```jl
julia> @time Pkg.add("Example")
  Installing known registries into `~/.julia`
     Cloning registry from "https://github.com/JuliaRegistries/General.git"
       Added registry `General` to `~/.julia/registries/General`
   Resolving package versions...
    Updating `/tmp/jl_nJuAcb/Project.toml`
  [7876af07] + Example v0.5.3
    Updating `/tmp/jl_nJuAcb/Manifest.toml`
  [7876af07] + Example v0.5.3
 15.838710 seconds (8.68 M allocations: 301.542 MiB, 0.29% gc time, 1.04% compilation time)
```

**pkg server**:

```
julia> @time Pkg.add("Example")
  Installing known registries into `~/.julia`
    Updating registry at `~/.julia/registries/General.toml`
   Resolving package versions...
    Updating `/tmp/jl_16gHZs/Project.toml`
  [7876af07] + Example v0.5.3
    Updating `/tmp/jl_16gHZs/Manifest.toml`
  [7876af07] + Example v0.5.3
  2.753616 seconds (5.57 M allocations: 355.760 MiB, 1.80% gc time, 0.09% compilation time)
```

This is on my Linux machine with a fast hard drive. On windows, the difference is much larger.

By the time https://github.com/julia-actions/julia-buildpkg/pull/6 was merged, the Pkg server would only serve the updated General once all the packages and artifacts were available. This is no longer the case and the Pkg server serves the updated registry straight away.

**Comment by xlxs4** [comment]
Hi! What's the status with this? The Windows times could be shortened *a lot*

**Comment by DilumAluthge** [comment]
I'm fine with switching to the Pkg server by default, as long as we set the `JULIA_PKG_SERVER_REGISTRY_PREFERENCE` environment variable to `eager` before we download the registry.

@SaschaMann @tkf @IanButterworth Does that sound good to you? We could still offer the old behavior with a flag.

**Comment by SaschaMann** [comment]
Sounds good, could you open a PR?
