### ISSUE TITLE
Error cloning General registry using buildpkg v1.3.1

### ISSUE THREAD

**Issue by tdivoll** [julia-actions/julia-buildpkg#27]
I was encountering this error when building in the CI. The solution was to roll back to `- uses: julia-actions/julia-buildpkg@v1.2.0` in CI.yml

![image](https://user-images.githubusercontent.com/24841909/208504561-624c183b-ca8e-4766-b375-bf77ee27dcf7.png)

**Comment by DilumAluthge** [comment]
@IanButterworth

**Comment by IanButterworth** [comment]
Eek. Sorry, I'll submit a PR shortly
